name: postgresql

services:
  timescaledb:
    image: postgres:17.0
    container_name: "posgresql"
    shm_size: 128m
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ./data:/var/lib/postgresql/data

secrets:
  db_password:
    file: ../secrets/db_password.secret
