name: pathfinder_runner

services:
  madara:
    image: pathfinder:latest
    container_name: "pathfinder_runner"
    cpu_count: 4
    mem_limit: "16gb"
    ports:
      - "9545"
    environment:
      RPC_API_KEY_FILE: /run/secrets/rpc_api_key
      GATEWAY_KEY_FILE: /run/secrets/gateway_key
    secrets:
      - rpc_api_key
      - gateway_key
    volumes:
      - type: volume
        source: db
        target: /data
        volume:
          nocopy: true

secrets:
  rpc_api_key:
    file: ../secrets/rpc_api_ws.secret
  gateway_key:
    file: ../secrets/gateway_key.secret

volumes:
  db:
