name: pathfinder_runner

services:
  fgw_health_pathfinder:
    image: busybox:1.36-glibc
    container_name: "fgw_health_pathfinder"
    external_links:
      - fgw_health_pathfinder
    networks:
      - fgw_network
    command: >
      sh -c '
        until ping fgw:8080 -c 1; do
          sleep 5
        done
      '
    restart: "no"
    init: true

  pathfinder:
    image: pathfinder:latest
    container_name: "pathfinder_runner"
    cpu_count: 4
    mem_limit: "16gb"
    ports:
      - "9545"
    environment:
      RPC_API_KEY_FILE: /run/secrets/rpc_api_key
    secrets:
      - rpc_api_key
    volumes:
      - type: volume
        source: db
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./pathfinder-runner.sh
        target: /usr/local/bin/runner.sh
        read_only: true
        bind:
          create_host_path: false
    networks:
      - fgw_network
    depends_on:
      fgw_health_pathfinder:
        condition: service_completed_successfully

secrets:
  rpc_api_key:
    file: ../secrets/rpc_api.secret

volumes:
  db:

networks:
  fgw_network:
    name: fgw_network
    external: true
